### ISSUE TITLE
DTR/ETR/vDTR results have degK to degC temperature conversion applied

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#12] opened 2023-02-11 03:29 UTC
I'm not sure if this is an icclim issue or a run_icclim.py issue but I've found that DTR/vDTR/EDTR variables have 273.15 subtracted from the results. It appears that the conversion from degK to degC is being applied after the index calculation. 

![image](https://user-images.githubusercontent.com/34051150/218236717-f26c39ad-b1a2-4801-bda1-997e8b4e0d7e.png)

**Comment by DamienIrving** [comment] 2023-02-13 22:27
Looks like it's a problem with icclim - I've submitted an issue to the developers: https://github.com/cerfacs-globc/icclim/issues/255

Do you want me to implement a temporary fix in `run_icclim.py` until the problem is resolved in the icclim package itself?

**Comment by ngben** [comment] 2023-02-13 22:32
Thanks Damien, it's not urgent so we can wait until icclim fixes it.

**Comment by ngben** [comment] 2023-04-02 06:59
I think this has been fixed in icclim 6.3.0

**Comment by DamienIrving** [comment] 2023-04-02 22:16
Yep, they fixed it last week (https://github.com/cerfacs-globc/icclim/pull/258) so it should be in the next release.

**Comment by DamienIrving** [comment] 2023-04-27 21:36
6.3.0 is out now :smile:

**Closed as completed by DamienIrving** 2023-04-27 21:36 UTC
